language: node_js
node_js: "node"

addons:
  apt:
    packages:
      - xmlstarlet

# branches:
#   only:
#     - master
#     - dev

# env:
#     - EMBER_VERSION=default
#     - EMBER_VERSION=release
#     - EMBER_VERSION=beta
#     - EMBER_VERSION=canary

# matrix:
#   fast_finish: true
#   allow_failures:
#     - env: EMBER_VERSION=release
#     - env: EMBER_VERSION=beta
#     - env: EMBER_VERSION=canary

# before_install:
#    - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
#    - "npm config set spin false"

install:
    - npm install svg2png@3.1.1
    - npm update   || true
    - npm outdated || true
    - npm ls       || true

before_script:
   - mkdir -p svg-out
   - mkdir -p png-out

script:
    - ls -ltr
    - make svg
    - ls svg-out
    - make png
    - ls png-out

# deploy:
#   provider: releases
#   skip_cleanup: false
#   github_token: ${GH_TOKEN}
#   local_dir: build/html
#   on:
#     branch: master
